### ISSUE TITLE
windowの候補が表示されない。

### ISSUE THREAD

**Issue by hokorobi** [kamecha/ddu-source-window#1]
# Problems summary

windowの候補が表示されない。

## Environment Information

- ddu.vim version (SHA1): d6dd2600

- denops.vim version (SHA1): 6b29032

- deno version(`deno -V` output): 1.33.3

- OS: Windows11

- neovim/Vim `:version` output:
VIM - Vi IMproved 9.0 (2022 Jun 28, compiled May 12 2023 22:52:27)
MS-Windows 64 ビット GUI 版 with OLE サポート
適用済パッチ: 1-1547
Compiled by appveyor@APPVEYOR-VM
Huge 版 with GUI.  機能の一覧 有効(+)/無効(-)
+acl                +cindent            +cursorshape        -farsi              +job                +menu               +packages           +reltime            -sun_workshop       -tgetent            +visualextra
+arabic             +clientserver       +dialog_con_gui     +file_in_path       +jumplist           +mksession          +path_extra         +rightleft          +syntax             +timers             +vreplace
+autocmd            +clipboard          +diff               +find_in_path       +keymap             +modify_fname       +perl/dyn           +ruby/dyn           +tag_binary         +title              -vtp
+autochdir          +cmdline_compl      +digraphs           +float              +lambda             +mouse              +persistent_undo    +scrollbind         -tag_old_static     +toolbar            +wildignore
+autoservername     +cmdline_hist       +directx            +folding            +langmap            +mouseshape         +popupwin           +signs              -tag_any_white      +user_commands      +wildmenu
+balloon_eval       +cmdline_info       -dnd                -footer             +libcall            +multi_byte_ime/dyn -postscript         +smartindent        -tcl                +vartabs            +windows
-balloon_eval_term  +comments           -ebcdic             +gettext/dyn        +linebreak          +multi_lang         +printer            +sodium/dyn         -termguicolors      +vertsplit          +writebackup
+browse             +conceal            +emacs_tags         -hangul_input       +lispindent         +mzscheme/dyn       +profile            +sound              +terminal           +vim9script         -xfontset
++builtin_terms     +cryptv             +eval               +iconv/dyn          +listcmds           +netbeans_intg      +python/dyn         +spell              -termresponse       +viminfo            -xim
+byte_offset        +cscope             +ex_extra           +insert_expand      +localmap           +num64              +python3/dyn        +startuptime        +textobjects        +virtualedit        +xpm_w32
+channel            +cursorbind         +extra_search       +ipv6               +lua/dyn            +ole                +quickfix           +statusline         +textprop           +visual             -xterm_save
      システム vimrc: "$VIM\vimrc"
      ユーザー vimrc: "$HOME\_vimrc"
   第2ユーザー vimrc: "$HOME\vimfiles\vimrc"
   第3ユーザー vimrc: "$VIM\_vimrc"
       ユーザー exrc: "$HOME\_exrc"
    第2ユーザー exrc: "$VIM\_exrc"
     システム gvimrc: "$VIM\gvimrc"
     ユーザー gvimrc: "$HOME\_gvimrc"
  第2ユーザー gvimrc: "$HOME\vimfiles\gvimrc"
  第3ユーザー gvimrc: "$VIM\_gvimrc"
  デフォルトファイル: "$VIMRUNTIME\defaults.vim"
    システムメニュー: "$VIMRUNTIME\menu.vim"
コンパイル: cl -c /W3 /GF /nologo -I. -Iproto -DHAVE_PATHDEF -DWIN32 -DHAVE_STDINT_H  -DFEAT_CSCOPE -DFEAT_TERMINAL -DFEAT_SOUND -DFEAT_NETBEANS_INTG -DFEAT_JOB_CHANNEL -DFEAT_IPV6 -DHAVE_INET_NTOP   -DFEAT_XPM_W32 -DHAVE_SODIUM -DDYNAMIC_SODIUM -DDYNAMIC_SODIUM_DLL=\"libsodium.dll\" /I "C:\projects\vim-win32-installer\dependencies\libsodium\include" -DWINVER=0x0601 -D_WIN32_WINNT=0x0601 /source-charset:utf-8 /MP /Ox /GL -DNDEBUG /Zl /MT /D_CRT_SECURE_NO_DEPRECATE /D_CRT_NONSTDC_NO_DEPRECATE -DFEAT_OLE -DFEAT_MBYTE_IME -DDYNAMIC_IME -DFEAT_GUI_MSWIN -DFEAT_DIRECTX -DDYNAMIC_DIRECTX -DFEAT_DIRECTX_COLOR_EMOJI -DDYNAMIC_ICONV -DDYNAMIC_GETTEXT -DFEAT_LUA -DDYNAMIC_LUA -DDYNAMIC_LUA_DLL=\"lua54.dll\" -DFEAT_PYTHON -DDYNAMIC_PYTHON -DDYNAMIC_PYTHON_DLL=\"python27.dll\" -DFEAT_PYTHON3 -DDYNAMIC_PYTHON3 -DDYNAMIC_PYTHON3_DLL=\"python311.dll\" -DFEAT_MZSCHEME -I "C:\projects\vim-win32-installer\dependencies\racket\include" -DMZ_PRECISE_GC -DDYNAMIC_MZSCHEME -DDYNAMIC_MZSCH_DLL=\"libracket3m_dcgt6o.dll\" -DDYNAMIC_MZGC_DLL=\"libracket3m_dcgt6o.dll\" -DFEAT_PERL -DPERL_IMPLICIT_CONTEXT -DPERL_IMPLICIT_SYS -DDYNAMIC_PERL -DDYNAMIC_PERL_DLL=\"perl532.dll\" -DFEAT_RUBY -DDYNAMIC_RUBY -DDYNAMIC_RUBY_DLL=\"x64-msvcrt-ruby300.dll\" -DRUBY_VERSION=30 -DFEAT_HUGE /Fd.\ObjGXOULYHRZAMD64/ /Zi
リンク: link /nologo /opt:ref /LTCG /HIGHENTROPYVA:NO oldnames.lib kernel32.lib advapi32.lib shell32.lib gdi32.lib  comdlg32.lib ole32.lib netapi32.lib uuid.lib user32.lib  /machine:AMD64 version.lib  winspool.lib comctl32.lib libcmt.lib oleaut32.lib  /nodefaultlib:lua54.lib  /STACK:8388608  /nodefaultlib:python27.lib /nodefaultlib:python311.lib    winmm.lib WSock32.lib Ws2_32.lib xpm\x64\lib-vc14\libXpm.lib  /PDB:gvim.pdb -debug

## Provide a minimal init.vim/vimrc

~/vimfiles/vimrc-min-ddu-window
```vim
set nocompatible
let $path .= ';' .. '~/.deno/bin'
set runtimepath+=C:\Users\hokorobi\_vim\dein\repos\github.com\vim-denops\denops.vim
set runtimepath+=C:\Users\hokorobi\_vim\dein\repos\github.com\Shougo\ddu.vim
set runtimepath+=C:\Users\hokorobi\_vim\dein\repos\github.com\Shougo\ddu-ui-ff
set runtimepath+=C:\Users\hokorobi\_vim\dein\repos\github.com\Shougo\ddu-filter-matcher_substring
set runtimepath+=C:\Users\hokorobi\_vim\dein\repos\github.com\Shougo\ddu-commands.vim
set runtimepath+=C:\Users\hokorobi\_vim\dein\repos\github.com\kamecha\ddu-source-window

call ddu#custom#patch_global(#{
    \   ui: 'ff',
    \   kindOptions: #{
    \     window: #{defaultAction: 'open'},
    \   },
    \   sourceOptions: #{
    \     _: #{
    \       ignoreCase: v:true,
    \       matchers: ['matcher_substring'],
    \     },
    \   },
    \   sources: [
    \     #{name: 'window', params: #{format: 'tab\|%n:%w:%wn'}},
    \   ],
    \   uiParams: #{
    \     ff: #{
    \       startFilter: v:true,
    \       autoAction: #{name: 'preview'},
    \       split: 'floating',
    \     }
    \   },
    \ })
autocmd Filetype ddu-ff nnoremap <buffer><silent> <CR> <Cmd>call ddu#ui#ff#do_action('itemAction')<CR>
autocmd Filetype ddu-ff nnoremap <buffer><silent> q <Cmd>call ddu#ui#ff#do_action('quit')<CR>
autocmd Filetype ddu-ff-filter inoremap <buffer><silent> <CR> <Esc><Cmd>close<CR><Cmd>call ddu#ui#ff#do_action('itemAction')<CR>
autocmd Filetype ddu-ff-filter nnoremap <buffer><silent> <CR> <Cmd>close<CR>
autocmd Filetype ddu-ff-filter nnoremap <buffer><silent> <Esc> <Cmd>close<CR>

filetype plugin indent on
syntax enable
```

## How to reproduce the problem from neovim/Vim startup (Required!)

1. gvim.exe -N -u ~/vimfiles/vimrc-min-ddu-window -U NONE -i NONE
2. :Ddu window

## Screenshot (if possible)
![image](https://github.com/kamecha/ddu-source-window/assets/99910/a7d01499-4560-4b2b-a99d-04fa85e80729)

## Upload the log messages by `:redir` and `:message` (if errored)
![image](https://github.com/kamecha/ddu-source-window/assets/99910/4d262e04-627e-47f2-b8f3-e966318771de)

**Comment by kamecha** [comment]
名前空間を意識した関数に変更したため、このエラー（未知の関数です）は出なくなると思います。

gVimでの検証はまだできておらず、時間を見つけ次第検証を行います。


I think that this error (unknown function) will not occur because the function has been changed to be aware of the namespace.

I haven't tested it with gVim yet, and will do so when I find time.

**Comment by hokorobi** [comment]
個人的にはクローズで良いと思っていますが、そのままにした方が良いでしょうか？

**Comment by kamecha** [comment]
自分の環境下のGvimでまだ試せていないため、どうしようかな、と考えていたのですが

時間がかかりそうなため、一旦閉じちゃおうと思います

知らせてくださり、ありがとうございます！
